# Generated by Django 4.1.1 on 2024-02-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_todo_completed_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
