# Generated by Django 4.1.1 on 2024-02-27 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_todopage_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('todo_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.todopage')),
            ],
        ),
    ]
