# Generated by Django 4.1.1 on 2024-02-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_todocategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todocategory',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='todopage',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
