# Generated by Django 4.1.1 on 2024-02-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_todocategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='todocategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
