# Generated by Django 4.1.1 on 2024-02-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_todocategory_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todocategory',
            options={'ordering': ['order']},
        ),
    ]
